[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Display Evolved name in rarity
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if AUT.card_type == 'Joker' or (AUT.badges and AUT.badges.force_rarity) then card_type = ({localize('k_common'), localize('k_uncommon'), localize('k_rare'), localize('k_legendary')})[card.config.center.rarity] end"
position = "at"
payload = "if AUT.card_type == 'Joker' or (AUT.badges and AUT.badges.force_rarity) then card_type = ({localize('k_common'), localize('k_uncommon'), localize('k_rare'), localize('k_legendary'), ['evo'] = 'Evolved'})[card.config.center.rarity] end"
match_indent = true

# Localization color
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "legendary = G.C.RARITY[4],"
position = "after"
payload = "evo = G.C.RARITY['evo'], heart = G.C.SUITS.Hearts, diamond = G.C.SUITS.Diamonds, spade = G.C.SUITS.Spades, club = G.C.SUITS.Clubs,"
match_indent = true

# Increment joker req
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.jokers.cards[i]:calculate_rental()"
position = "before"
payload = """
if G.GAME.blind.boss and G.jokers.cards[i].ability.req then
    sendDebugMessage(inspect(G.jokers.cards[i]:generate_UIBox_ability_table()))
    G.jokers.cards[i]:calculate_evo("boss")
end
"""
match_indent = true

# Add req amount tooltip to vanilla joker
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "elseif _c.name == 'Perkeo' then info_queue[#info_queue+1] = {key = 'e_negative_consumable', set = 'Edition', config = {extra = 1}}"
position = "after"
payload = """
elseif has_evo(_c) then info_queue[#info_queue + 1] = set_evo_tooltip(_c)
"""
match_indent = true