[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# sdm_adding_card context

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.edition and self.edition.negative then"
position = "before"
payload = """
if G.jokers and #G.jokers.cards > 0 then
    for i = 1, #G.jokers.cards do
        G.jokers.cards[i]:calculate_joker({sdm_adding_card = true, card = self})
    end
end
"""
match_indent = true
